#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
#[repr(u32)]
pub enum AssetType {
    PhysPreset = 0x00,
    PhysCollmap = 0x01,
    XAnimParts = 0x02,
    XModelSurfs = 0x03,
    XModel = 0x04,
    Material = 0x05,
    PixelShader = 0x06,
    VertexShader = 0x07,
    VertexDecl = 0x08,
    TechniqueSet = 0x09,
    Image = 0x0A,
    Sound = 0x0B,
    SoundCurve = 0x0C,
    LoadedSound = 0x0D,
    ClipMapSp = 0x0E,
    ClipMapMp = 0x0F,
    ComWorld = 0x10,
    GameWorldSp = 0x11,
    GameWorldMp = 0x12,
    MapEnts = 0x13,
    FxWorld = 0x14,
    GfxWorld = 0x15,
    LightDef = 0x16,
    UiMap = 0x17,
    Font = 0x18,
    MenuList = 0x19,
    Menu = 0x1A,
    Localize = 0x1B,
    Weapon = 0x1C,
    SndDriverGlobals = 0x1D,
    Fx = 0x1E,
    ImpactFx = 0x1F,
    AiType = 0x20,
    MpType = 0x21,
    Character = 0x22,
    XModelAlias = 0x23,
    RawFile = 0x24,
    StringTable = 0x25,
    LeaderBoard = 0x26,
    StructuredDataDef = 0x27,
    Tracer = 0x28,
    Vehicle = 0x29,
    AddonMapEnts = 0x2A,
}

impl AssetType {
    pub const fn from_u32(v: u32) -> Option<AssetType> {
        use AssetType::*;
        Some(match v {
            0x00 => PhysPreset,
            0x01 => PhysCollmap,
            0x02 => XAnimParts,
            0x03 => XModelSurfs,
            0x04 => XModel,
            0x05 => Material,
            0x06 => PixelShader,
            0x07 => VertexShader,
            0x08 => VertexDecl,
            0x09 => TechniqueSet,
            0x0A => Image,
            0x0B => Sound,
            0x0C => SoundCurve,
            0x0D => LoadedSound,
            0x0E => ClipMapSp,
            0x0F => ClipMapMp,
            0x10 => ComWorld,
            0x11 => GameWorldSp,
            0x12 => GameWorldMp,
            0x13 => MapEnts,
            0x14 => FxWorld,
            0x15 => GfxWorld,
            0x16 => LightDef,
            0x17 => UiMap,
            0x18 => Font,
            0x19 => MenuList,
            0x1A => Menu,
            0x1B => Localize,
            0x1C => Weapon,
            0x1D => SndDriverGlobals,
            0x1E => Fx,
            0x1F => ImpactFx,
            0x20 => AiType,
            0x21 => MpType,
            0x22 => Character,
            0x23 => XModelAlias,
            0x24 => RawFile,
            0x25 => StringTable,
            0x26 => LeaderBoard,
            0x27 => StructuredDataDef,
            0x28 => Tracer,
            0x29 => Vehicle,
            0x2A => AddonMapEnts,
            _ => return None,
        })
    }

    pub const fn name(self) -> &'static str {
        use AssetType::*;
        match self {
            PhysPreset => "physpreset",
            PhysCollmap => "physcollmap",
            XAnimParts => "xanim",
            XModelSurfs => "xmodelsurfs",
            XModel => "xmodel",
            Material => "material",
            PixelShader => "pixelshader",
            VertexShader => "vertexshader",
            VertexDecl => "vertexdecl",
            TechniqueSet => "techniqueset",
            Image => "image",
            Sound => "sound",
            SoundCurve => "soundcurve",
            LoadedSound => "loadedsound",
            ClipMapSp => "clipmapsp",
            ClipMapMp => "clipmap",
            ComWorld => "comworld",
            GameWorldSp => "gameworldsp",
            GameWorldMp => "gameworldmp",
            MapEnts => "mapents",
            FxWorld => "fxworld",
            GfxWorld => "gfxworld",
            LightDef => "lightdef",
            UiMap => "uimap",
            Font => "font",
            MenuList => "menulist",
            Menu => "menu",
            Localize => "localize",
            Weapon => "weapon",
            SndDriverGlobals => "snddriverglobals",
            Fx => "fx",
            ImpactFx => "impactfx",
            AiType => "aitype",
            MpType => "mptype",
            Character => "character",
            XModelAlias => "xmodelalias",
            RawFile => "rawfile",
            StringTable => "stringtable",
            LeaderBoard => "leaderboard",
            StructuredDataDef => "structureddatadef",
            Tracer => "tracer",
            Vehicle => "vehicle",
            AddonMapEnts => "addonmapents",
        }
    }
}
