#[derive(Clone, Copy, Debug, PartialEq)]
pub struct XAnimParts {
    pub numframes: u16,
    pub flags: u8,
    pub bone_count_no_quat: u8,
    pub bone_count_half_quat: u8,
    pub bone_count_full_quat: u8,
    pub bone_count_half_quat_no_size: u8,
    pub bone_count_full_quat_no_size: u8,
    pub bone_count_small_trans: u8,
    pub bone_count_trans: u8,
    pub bone_count_trans_no_size: u8,
    pub bone_count_no_trans: u8,
    pub bone_count_all: u8,
    pub names: u32,
    pub data_byte: u32,
    pub data_short: u32,
    pub data_int: u32,
    pub random_data_short: u32,
    pub random_data_byte: u32,
}
