#[derive(Clone, Copy, Debug, PartialEq)]
pub struct FxElemDef {
    pub flags: i32,
    pub spawn: [u8; 8],
    pub spawn_range: [u8; 8],
    pub fade_in_range: [u8; 8],
    pub fade_out_range: [u8; 8],
    pub spawn_frustum_cull_radius: f32,
    pub spawn_delay_msec: [u8; 8],
    pub life_span_msec: [u8; 8],
    pub spawn_origin: [u8; 24],
    pub spawn_offset_radius: [u8; 8],
    pub spawn_offset_height: [u8; 8],
    pub spawn_angles: [u8; 24],
    pub angular_velocity: [u8; 24],
    pub initial_rotation: [u8; 8],
    pub gravity: [u8; 8],
    pub reflection_factor: [u8; 8],
    pub elem_type: u8,
    pub visual_count: u8,
    pub vel_interval_count: u8,
    pub vis_state_interval_count: u8,
    pub vel_samples: u32,
    pub vis_samples: u32,
    pub visuals: u32,
    pub coll_bounds: [u8; 24],
    pub effect_on_impact: u32,
    pub effect_on_death: u32,
    pub effect_emitted: u32,
    pub emit_dist: [u8; 8],
    pub emit_dist_variance: [u8; 8],
    pub extended: u32,
    pub sort_order: u8,
    pub lighting_frac: u8,
    pub use_item_clip: u8,
}
