/// `XAssetType` as the zone's asset array spells it.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(u32)]
pub enum AssetType {
    XModelPieces = 0,
    PhysPreset = 1,
    PhysConstraints = 2,
    DestructibleDef = 3,
    XAnimParts = 4,
    XModel = 5,
    Material = 6,
    TechniqueSet = 7,
    Image = 8,
    SoundBank = 9,
    SoundPatch = 10,
    ClipMap = 11,
    ClipMapPvs = 12,
    ComWorld = 13,
    GameWorldSp = 14,
    GameWorldMp = 15,
    MapEnts = 16,
    GfxWorld = 17,
    LightDef = 18,
    UiMap = 19,
    Font = 20,
    FontIcon = 21,
    MenuList = 22,
    Menu = 23,
    LocalizeEntry = 24,
    Weapon = 25,
    WeaponDef = 26,
    WeaponVariant = 27,
    WeaponFull = 28,
    Attachment = 29,
    AttachmentUnique = 30,
    WeaponCamo = 31,
    SndDriverGlobals = 32,
    Fx = 33,
    ImpactFx = 34,
    AiType = 35,
    MpType = 36,
    MpBody = 37,
    MpHead = 38,
    Character = 39,
    XModelAlias = 40,
    RawFile = 41,
    StringTable = 42,
    Leaderboard = 43,
    XGlobals = 44,
    Ddl = 45,
    Glasses = 46,
    EmblemSet = 47,
    Script = 48,
    KeyValuePairs = 49,
    Vehicle = 50,
    MemoryBlock = 51,
    AddonMapEnts = 52,
    Tracer = 53,
    SkinnedVerts = 54,
    Qdb = 55,
    Slug = 56,
    FootstepTable = 57,
    FootstepFxTable = 58,
    ZBarrier = 59,
}

impl AssetType {
    const ALL: [AssetType; 60] = [
        Self::XModelPieces,
        Self::PhysPreset,
        Self::PhysConstraints,
        Self::DestructibleDef,
        Self::XAnimParts,
        Self::XModel,
        Self::Material,
        Self::TechniqueSet,
        Self::Image,
        Self::SoundBank,
        Self::SoundPatch,
        Self::ClipMap,
        Self::ClipMapPvs,
        Self::ComWorld,
        Self::GameWorldSp,
        Self::GameWorldMp,
        Self::MapEnts,
        Self::GfxWorld,
        Self::LightDef,
        Self::UiMap,
        Self::Font,
        Self::FontIcon,
        Self::MenuList,
        Self::Menu,
        Self::LocalizeEntry,
        Self::Weapon,
        Self::WeaponDef,
        Self::WeaponVariant,
        Self::WeaponFull,
        Self::Attachment,
        Self::AttachmentUnique,
        Self::WeaponCamo,
        Self::SndDriverGlobals,
        Self::Fx,
        Self::ImpactFx,
        Self::AiType,
        Self::MpType,
        Self::MpBody,
        Self::MpHead,
        Self::Character,
        Self::XModelAlias,
        Self::RawFile,
        Self::StringTable,
        Self::Leaderboard,
        Self::XGlobals,
        Self::Ddl,
        Self::Glasses,
        Self::EmblemSet,
        Self::Script,
        Self::KeyValuePairs,
        Self::Vehicle,
        Self::MemoryBlock,
        Self::AddonMapEnts,
        Self::Tracer,
        Self::SkinnedVerts,
        Self::Qdb,
        Self::Slug,
        Self::FootstepTable,
        Self::FootstepFxTable,
        Self::ZBarrier,
    ];

    pub fn from_u32(raw: u32) -> Option<Self> {
        Self::ALL.get(raw as usize).copied()
    }
}
