#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
#[repr(u32)]
pub enum AssetType {
    XModelPieces = 0x00,
    PhysPreset = 0x01,
    PhysConstraints = 0x02,
    DestructibleDef = 0x03,
    XAnimParts = 0x04,
    XModel = 0x05,
    Material = 0x06,
    TechniqueSet = 0x07,
    Image = 0x08,
    Sound = 0x09,
    SoundPatch = 0x0A,
    ClipMapSp = 0x0B,
    ClipMapMp = 0x0C,
    ComWorld = 0x0D,
    GameWorldSp = 0x0E,
    GameWorldMp = 0x0F,
    MapEnts = 0x10,
    GfxWorld = 0x11,
    LightDef = 0x12,
    UiMap = 0x13,
    Font = 0x14,
    MenuList = 0x15,
    Menu = 0x16,
    Localize = 0x17,
    Weapon = 0x18,
    WeaponDef = 0x19,
    WeaponVariant = 0x1A,
    SndDriverGlobals = 0x1B,
    Fx = 0x1C,
    ImpactFx = 0x1D,
    AiType = 0x1E,
    MpType = 0x1F,
    MpBody = 0x20,
    MpHead = 0x21,
    Character = 0x22,
    XModelAlias = 0x23,
    RawFile = 0x24,
    StringTable = 0x25,
    PackIndex = 0x26,
    XGlobals = 0x27,
    Ddl = 0x28,
    Glasses = 0x29,
    EmblemSet = 0x2A,
}

impl AssetType {
    pub const fn from_u32(v: u32) -> Option<AssetType> {
        use AssetType::*;
        Some(match v {
            0x00 => XModelPieces,
            0x01 => PhysPreset,
            0x02 => PhysConstraints,
            0x03 => DestructibleDef,
            0x04 => XAnimParts,
            0x05 => XModel,
            0x06 => Material,
            0x07 => TechniqueSet,
            0x08 => Image,
            0x09 => Sound,
            0x0A => SoundPatch,
            0x0B => ClipMapSp,
            0x0C => ClipMapMp,
            0x0D => ComWorld,
            0x0E => GameWorldSp,
            0x0F => GameWorldMp,
            0x10 => MapEnts,
            0x11 => GfxWorld,
            0x12 => LightDef,
            0x13 => UiMap,
            0x14 => Font,
            0x15 => MenuList,
            0x16 => Menu,
            0x17 => Localize,
            0x18 => Weapon,
            0x19 => WeaponDef,
            0x1A => WeaponVariant,
            0x1B => SndDriverGlobals,
            0x1C => Fx,
            0x1D => ImpactFx,
            0x1E => AiType,
            0x1F => MpType,
            0x20 => MpBody,
            0x21 => MpHead,
            0x22 => Character,
            0x23 => XModelAlias,
            0x24 => RawFile,
            0x25 => StringTable,
            0x26 => PackIndex,
            0x27 => XGlobals,
            0x28 => Ddl,
            0x29 => Glasses,
            0x2A => EmblemSet,
            _ => return None,
        })
    }

    pub const fn name(self) -> &'static str {
        use AssetType::*;
        match self {
            XModelPieces => "xmodelpieces",
            PhysPreset => "physpreset",
            PhysConstraints => "physconstraints",
            DestructibleDef => "destructibledef",
            XAnimParts => "xanim",
            XModel => "xmodel",
            Material => "material",
            TechniqueSet => "techset",
            Image => "image",
            Sound => "sound",
            SoundPatch => "sound_patch",
            ClipMapSp => "col_map_sp",
            ClipMapMp => "col_map_mp",
            ComWorld => "com_map",
            GameWorldSp => "game_map_sp",
            GameWorldMp => "game_map_mp",
            MapEnts => "map_ents",
            GfxWorld => "gfx_map",
            LightDef => "lightdef",
            UiMap => "ui_map",
            Font => "font",
            MenuList => "menufile",
            Menu => "menu",
            Localize => "localize",
            Weapon => "weapon",
            WeaponDef => "weapondef",
            WeaponVariant => "weaponvariant",
            SndDriverGlobals => "snddriverglobals",
            Fx => "fx",
            ImpactFx => "impactfx",
            AiType => "aitype",
            MpType => "mptype",
            MpBody => "mpbody",
            MpHead => "mphead",
            Character => "character",
            XModelAlias => "xmodelalias",
            RawFile => "rawfile",
            StringTable => "stringtable",
            PackIndex => "packindex",
            XGlobals => "xGlobals",
            Ddl => "ddl",
            Glasses => "glasses",
            EmblemSet => "emblemset",
        }
    }
}
