#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
#[repr(u32)]
pub enum AssetType {
    PhysPreset = 0x00,
    PhysCollMap = 0x01,
    XAnimParts = 0x02,
    XModelSurfs = 0x03,
    XModel = 0x04,
    Material = 0x05,
    PixelShader = 0x06,
    VertexShader = 0x07,
    VertexDecl = 0x08,
    TechniqueSet = 0x09,
    Image = 0x0A,
    Sound = 0x0B,
    SoundCurve = 0x0C,
    LoadedSound = 0x0D,
    ClipMap = 0x0E,
    ComWorld = 0x0F,
    GlassWorld = 0x10,
    PathData = 0x11,
    VehicleTrack = 0x12,
    MapEnts = 0x13,
    FxWorld = 0x14,
    GfxWorld = 0x15,
    LightDef = 0x16,
    UiMap = 0x17,
    Font = 0x18,
    MenuList = 0x19,
    Menu = 0x1A,
    Localize = 0x1B,
    Attachment = 0x1C,
    Weapon = 0x1D,
    SndDriverGlobals = 0x1E,
    Fx = 0x1F,
    ImpactFx = 0x20,
    SurfaceFx = 0x21,
    AiType = 0x22,
    MpType = 0x23,
    Character = 0x24,
    XModelAlias = 0x25,
    RawFile = 0x26,
    ScriptFile = 0x27,
    StringTable = 0x28,
    Leaderboard = 0x29,
    StructuredDataDef = 0x2A,
    Tracer = 0x2B,
    Vehicle = 0x2C,
    AddonMapEnts = 0x2D,
}

impl AssetType {
    pub const fn from_u32(v: u32) -> Option<AssetType> {
        use AssetType::*;
        Some(match v {
            0x00 => PhysPreset,
            0x01 => PhysCollMap,
            0x02 => XAnimParts,
            0x03 => XModelSurfs,
            0x04 => XModel,
            0x05 => Material,
            0x06 => PixelShader,
            0x07 => VertexShader,
            0x08 => VertexDecl,
            0x09 => TechniqueSet,
            0x0A => Image,
            0x0B => Sound,
            0x0C => SoundCurve,
            0x0D => LoadedSound,
            0x0E => ClipMap,
            0x0F => ComWorld,
            0x10 => GlassWorld,
            0x11 => PathData,
            0x12 => VehicleTrack,
            0x13 => MapEnts,
            0x14 => FxWorld,
            0x15 => GfxWorld,
            0x16 => LightDef,
            0x17 => UiMap,
            0x18 => Font,
            0x19 => MenuList,
            0x1A => Menu,
            0x1B => Localize,
            0x1C => Attachment,
            0x1D => Weapon,
            0x1E => SndDriverGlobals,
            0x1F => Fx,
            0x20 => ImpactFx,
            0x21 => SurfaceFx,
            0x22 => AiType,
            0x23 => MpType,
            0x24 => Character,
            0x25 => XModelAlias,
            0x26 => RawFile,
            0x27 => ScriptFile,
            0x28 => StringTable,
            0x29 => Leaderboard,
            0x2A => StructuredDataDef,
            0x2B => Tracer,
            0x2C => Vehicle,
            0x2D => AddonMapEnts,
            _ => return None,
        })
    }

    pub const fn name(self) -> &'static str {
        use AssetType::*;
        match self {
            PhysPreset => "physpreset",
            PhysCollMap => "phys_collmap",
            XAnimParts => "xanim",
            XModelSurfs => "xmodelsurfs",
            XModel => "xmodel",
            Material => "material",
            PixelShader => "pixelshader",
            VertexShader => "vertexshader",
            VertexDecl => "vertexdecl",
            TechniqueSet => "techset",
            Image => "image",
            Sound => "sound",
            SoundCurve => "sndcurve",
            LoadedSound => "loaded_sound",
            ClipMap => "col_map_mp",
            ComWorld => "com_map",
            GlassWorld => "glass_map",
            PathData => "aipaths",
            VehicleTrack => "vehicle_track",
            MapEnts => "map_ents",
            FxWorld => "fx_map",
            GfxWorld => "gfx_map",
            LightDef => "lightdef",
            UiMap => "ui_map",
            Font => "font",
            MenuList => "menufile",
            Menu => "menu",
            Localize => "localize",
            Attachment => "attachment",
            Weapon => "weapon",
            SndDriverGlobals => "snddriverglobals",
            Fx => "fx",
            ImpactFx => "impactfx",
            SurfaceFx => "surfacefx",
            AiType => "aitype",
            MpType => "mptype",
            Character => "character",
            XModelAlias => "xmodelalias",
            RawFile => "rawfile",
            ScriptFile => "scriptfile",
            StringTable => "stringtable",
            Leaderboard => "leaderboarddef",
            StructuredDataDef => "structureddatadef",
            Tracer => "tracer",
            Vehicle => "vehicle",
            AddonMapEnts => "addon_map_ents",
        }
    }
}
